// <auto-generated />
using System;
using AutomatedMarketIntelligenceTool.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomatedMarketIntelligenceTool.Infrastructure.Migrations
{
    [DbContext(typeof(AutomatedMarketIntelligenceToolContext))]
    [Migration("20260108210414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.ListingAggregate.Listing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyStyle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNewListing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ListingId");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Listing_Price");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Listing_TenantId");

                    b.HasIndex("Vin")
                        .HasDatabaseName("IX_Listing_Vin");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Listing_Year");

                    b.HasIndex("Make", "Model")
                        .HasDatabaseName("IX_Listing_MakeModel");

                    b.HasIndex("SourceSite", "ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Listing_External");

                    b.ToTable("Listings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
