// <auto-generated />
using System;
using AutomatedMarketIntelligenceTool.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomatedMarketIntelligenceTool.Infrastructure.Migrations
{
    [DbContext(typeof(AutomatedMarketIntelligenceToolContext))]
    [Migration("20260109212645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.AlertAggregate.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Criteria");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationTarget")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("AlertId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Alert_IsActive");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Alert_TenantId");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("IX_Alert_TenantName");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.AlertAggregate.AlertNotification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("IX_AlertNotification_AlertId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_AlertNotification_SentAt");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AlertNotification_TenantId");

                    b.ToTable("AlertNotifications", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.CacheAggregate.ResponseCacheEntry", b =>
                {
                    b.Property<Guid>("CacheEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("ResponseData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("ResponseSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("CacheEntryId");

                    b.HasIndex("CacheKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResponseCache_CacheKey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ResponseCache_ExpiresAt");

                    b.HasIndex("Url")
                        .HasDatabaseName("IX_ResponseCache_Url");

                    b.ToTable("ResponseCache", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.DealerAggregate.Dealer", b =>
                {
                    b.Property<Guid>("DealerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("DealerId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Dealer_NormalizedName");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Dealer_TenantId");

                    b.HasIndex("TenantId", "NormalizedName")
                        .HasDatabaseName("IX_Dealer_TenantNormalizedName");

                    b.ToTable("Dealers", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.ListingAggregate.Listing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BodyStyle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Condition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("CAD");

                    b.Property<int?>("DaysOnMarket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DealerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Drivetrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageHashes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsNewListing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedVehicleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ListingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MatchConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchMethod")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousListingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RelistedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SellerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SellerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListingId");

                    b.HasIndex("BodyStyle")
                        .HasDatabaseName("IX_Listing_BodyStyle");

                    b.HasIndex("Condition")
                        .HasDatabaseName("IX_Listing_Condition");

                    b.HasIndex("DealerId");

                    b.HasIndex("FirstSeenDate")
                        .HasDatabaseName("IX_Listing_FirstSeenDate");

                    b.HasIndex("FuelType")
                        .HasDatabaseName("IX_Listing_FuelType");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Listing_IsActive");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Listing_Price");

                    b.HasIndex("RelistedCount")
                        .HasDatabaseName("IX_Listing_RelistedCount")
                        .HasFilter("[RelistedCount] > 0");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Listing_TenantId");

                    b.HasIndex("Transmission")
                        .HasDatabaseName("IX_Listing_Transmission");

                    b.HasIndex("Vin")
                        .HasDatabaseName("IX_Listing_Vin");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Listing_Year");

                    b.HasIndex("CreatedAt", "TenantId")
                        .HasDatabaseName("IX_Listing_CreatedAt_TenantId");

                    b.HasIndex("Make", "Model")
                        .HasDatabaseName("IX_Listing_MakeModel");

                    b.HasIndex("Vin", "TenantId")
                        .HasDatabaseName("IX_Listing_Vin_TenantId");

                    b.HasIndex("SourceSite", "ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Listing_External");

                    b.HasIndex("Make", "Model", "Year", "TenantId")
                        .HasDatabaseName("IX_Listing_Make_Model_Year_TenantId");

                    b.HasIndex("TenantId", "IsActive", "Make", "Year")
                        .HasDatabaseName("IX_Listing_BatchDedup");

                    b.HasIndex("Make", "Year", "Price", "TenantId", "IsActive")
                        .HasDatabaseName("IX_Listing_FuzzyCandidate");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.PriceHistoryAggregate.PriceHistory", b =>
                {
                    b.Property<Guid>("PriceHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChangePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceChange")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("IX_PriceHistory_ListingId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PriceHistory_TenantId");

                    b.ToTable("PriceHistory", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.ReviewQueueAggregate.ReviewItem", b =>
                {
                    b.Property<Guid>("ReviewItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldScores")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Listing1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Listing2Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewItemId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Review_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Review_TenantId");

                    b.HasIndex("Listing1Id", "Listing2Id")
                        .HasDatabaseName("IX_Review_Listings");

                    b.ToTable("ReviewQueue", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.ScraperHealthAggregate.ScraperHealthRecord", b =>
                {
                    b.Property<Guid>("ScraperHealthRecordId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AverageResponseTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissingElementCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissingElementsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuccessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ScraperHealthRecordId");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("IX_Health_RecordedAt");

                    b.HasIndex("SiteName")
                        .HasDatabaseName("IX_Health_Site");

                    b.ToTable("ScraperHealth", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.SearchProfileAggregate.SearchProfile", b =>
                {
                    b.Property<Guid>("SearchProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SearchProfileId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("SearchProfiles", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.SearchSessionAggregate.SearchSession", b =>
                {
                    b.Property<Guid>("SearchSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewListingsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("PriceChangesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SearchParameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalListingsFound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("SearchSessionId");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_SearchSession_StartTime");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SearchSession_TenantId");

                    b.ToTable("SearchSessions", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.VehicleAggregate.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AveragePrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("BestPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryVin")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.HasIndex("PrimaryVin");

                    b.HasIndex("TenantId");

                    b.HasIndex("Make", "Model", "Year");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.WatchListAggregate.WatchedListing", b =>
                {
                    b.Property<Guid>("WatchedListingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnPriceChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifyOnRemoval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("WatchedListingId");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("IX_WatchedListing_ListingId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_WatchedListing_TenantId");

                    b.HasIndex("TenantId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("UQ_WatchedListing_TenantListing");

                    b.ToTable("WatchedListings", (string)null);
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.AlertAggregate.AlertNotification", b =>
                {
                    b.HasOne("AutomatedMarketIntelligenceTool.Core.Models.AlertAggregate.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomatedMarketIntelligenceTool.Core.Models.ListingAggregate.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.ListingAggregate.Listing", b =>
                {
                    b.HasOne("AutomatedMarketIntelligenceTool.Core.Models.DealerAggregate.Dealer", "DealerEntity")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DealerEntity");
                });

            modelBuilder.Entity("AutomatedMarketIntelligenceTool.Core.Models.WatchListAggregate.WatchedListing", b =>
                {
                    b.HasOne("AutomatedMarketIntelligenceTool.Core.Models.ListingAggregate.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });
#pragma warning restore 612, 618
        }
    }
}
